### ISSUE TITLE
[HOPP] Error: less function not found

### ISSUE THREAD

**Issue by Riotpiaole** [hoppjs/hopp#30]
```
✖ hopp TypeError: hopp(...).less is not a function
    at Object.<anonymous> (/Users/rockliang/Desktop/Project/hopp_open_source/hopp_less/hoppfile.js:6:6)
    at Module._compile (module.js:571:32)
```

```javascript
      const hopp=require('hopp')
 
   const less=
        hopp(['examples/less/*.less'])
        .less()
        .dest('dist/css')

     module.exports =less;
```

running ``` hopp  -H ``` obtain above error.

is that the doc is changed?

**Comment by karimsa** [comment]
Make sure you have installed (and saved) `hopp-preset-less` to the same directory as this hoppfile.

**Comment by karimsa** [comment]
Also, `hopp -H` is no longer supported. If you want to use ES2015 features in your hoppfile, the new way to do this in available [in the docs](http://docs.hoppjs.com/contents/overview/getting-started.html).
